Davidty143/purple-eclipse

.env
.eslintrc.json
app/(auth)/auth/confirm/route.ts
app/(auth)/signup/components/SignUpForm.tsx
lib/auth-actions.ts
next.config.mjs

- Fixed an issue with the incorrect URL being used in the environment configuration.
optimized: package imports for seamless page compile.
applied optimizePackageImports to packages from library to speed up the compile time when pages load.

fix: incorrect env URL

---

prisma/migrations/20250329063752_init/migration.sql
prisma/migrations/20250329063914_init/migration.sql
prisma/migrations/20250329065407_init/migration.sql
prisma/schema.prisma

will make a UI for  the forums first and will test the database functionality

add forum and subforum model and its attributes in the database schema

---

app/(landingPage)/components/PopularSubforums.tsx
app/forums/subforum/[subforumId]/components/SubforumTopics.tsx
app/layout/components/LoggedInHeaderRight.tsx
app/post-thread/components/PostThread.tsx
app/profile/components/UserProfile.tsx
app/profile/layout.tsx
app/profile/page.tsx
app/search/layout.tsx
app/search/page.tsx
app/thread/[threadId]/components/ThreadView.tsx
app/thread/[threadId]/edit/components/EditThreadForm.tsx
app/thread/[threadId]/edit/page.tsx
app/thread/[threadId]/page.tsx
components/SearchBar.tsx
components/ThreadRow.tsx
prisma/migrations/20250417022409_add_author_to_thread/migration.sql
prisma/schema.prisma

- Added `avatar_url` to author data across various components including `ThreadRow`, `ThreadView`, and `SubforumTopics` for improved user representation.
- Updated `PostThread` to include avatar URL during account creation.
- Refactored `PopularSubforums` and `SearchBar` components for better data handling and user experience.
- Improved error handling in data fetching processes and ensured null checks for author properties.
- Adjusted Prisma schema to support new avatar URL fields in the `Account` model.

Enhance user profile integration and thread display

---

app/search/page.tsx
app/thread/[threadId]/components/ThreadView.tsx
components/SearchBar.tsx

- Updated the search logic to include both thread titles and content, allowing for more comprehensive search results.
- Added a new search feature to filter threads by author username.
- Improved error handling for search results to display appropriate messages.
- Refactored the search results UI for better presentation, including a new layout and content preview.
- Enhanced the SearchBar component with a submit button and updated styling for a better user experience.

Enhance search functionality and UI improvements

---

app/search/page.tsx
components/SearchBar.tsx

- Updated the SearchPage component to include a search type parameter, allowing users to filter results by content, username, or all.
- Added a search type selector UI for improved user experience.
- Refactored the SearchResults function to handle different search types and ensure proper error handling.
- Improved the SearchBar component's styling for better usability.

Enhance search functionality with type filtering

---

jest.config.ts
jest.setup.ts
package-lock.json
package.json

Initial testing tool setup "Jest"

Initial Jest Setup

---

app/(landingPage)/components/NewTopics.tsx
app/(landingPage)/components/SidebarThreadRow.tsx

- Adjusted the width of the NewTopics card to be responsive, allowing it to take full width on smaller screens.
- Wrapped the SidebarThreadRow content in a Link component to enable navigation to the thread details page, enhancing user interaction.

Update NewTopics and SidebarThreadRow components for improved responsiveness

---

app/(auth)/login/components/LoginForm.tsx
app/(auth)/login/components/LoginOverlay.tsx
app/(auth)/login/components/SignInWithGoogleButton.tsx

Added loading states to disable buttons when one of them is clicked.

Fix: Added loading states for authentication buttons

---

app/profile/components/UserProfile.tsx
app/thread/[threadId]/edit/components/EditThreadForm.tsx

Refactor UserProfile and EditThreadForm components for improved content handling and UI consistency. Strip HTML tags from thread content in UserProfile and replace Textarea with RichTextEditor in EditThreadForm.

Refactor UserProfile and EditThreadForm 

---

app/latest/page.tsx

Implement a dropdown select for filtering threads by category, enhancing user experience. Update data fetching logic to accommodate the selected category and ensure the component re-renders accordingly.

Add category filter to latest threads page

---

app/landing-page/components/NewTopics.tsx

- Added a refreshThreads function to invalidate the cache and fetch new thread data.
- Implemented real-time subscription to listen for changes in the 'Thread' table, ensuring the component updates automatically when data changes.
- Refactored the useEffect hook to utilize the new refreshThreads function for initial data fetching and subscription management.

Enhance NewTopics component with real-time updates and cache invalidition

---

app/profile/components/UserProfile.tsx
app/thread/[threadId]/edit/components/EditThreadForm.tsx

- Corrected text in UserProfile component for consistency.
- Added an edit button for threads in UserProfile to improve user interaction.
- Updated comment in EditThreadForm to clarify redirection after thread updates.

Enhance UserProfile and EditThreadForm components

---

app/restricted/page.tsx
app/thread/[threadId]/components/CommentForm.tsx
components/BodyHeader.tsx
components/thread/ThreadForm.tsx
middleware.ts

- Updated middleware to include '/restricted' in allowed routes for better access control.
- Modified RestrictedPage to provide clearer messaging regarding account restrictions.
- Implemented user status checks in CommentForm, ThreadForm, and BodyHeader components to prevent restricted or banned users from posting comments or threads.
- Added a BanModal to inform users of their banned status with an option to contact support.
- Improved user experience by conditionally rendering UI elements based on account status.

Enhance user account status handling and UI updates

---

app/forums/components/SubforumCard.tsx
app/forums/subforum/[subforumId]/components/SubforumHeader.tsx
app/landing-page/components/SubforumBlock.tsx

- Added user role checks to SubforumCard and SubforumHeader components to conditionally render edit and delete actions for admins.
- Integrated Supabase authentication to manage user sessions and redirect unauthenticated users to the login page.
- Enhanced SubforumBlock to display a login overlay when unauthenticated users attempt to access subforum threads.

Implement user authentication checks and admin controls in Subforum components

---

app/layout/components/LoggedInHeaderRight.tsx
components/BodyHeader.tsx

- Simplified the logic for fetching and updating user account status.
- Removed unnecessary checks for null account status, enhancing clarity and efficiency in user status management.

Refactor account status handling in BodyHeader component

---

middleware.ts

- Updated the account data fetching logic to include 'restriction_reason' for better user management.
- Modified the handling of restricted users to clear all restriction-related fields when the restriction has expired, improving data integrity and clarity.

Enhance middleware to include restriction reason and clear restriction data upon status update

---

lib/auth-actions.ts
middleware.ts

- Added detailed logging for account status checks to improve debugging and monitoring.
- Updated middleware to handle date comparisons in UTC for accurate restriction status evaluation.
- Enhanced login function to check account status and restrictions for both username and email logins, ensuring users are informed of any bans or restrictions before proceeding.

Enhance account status checks in middleware and login function

---

app/api/account-status/route.ts
app/auth/callback/route.ts
app/components/AccountStatusChecker.tsx
app/layout.tsx
middleware.ts

- Introduced a new API route for checking and updating user account status upon login.
- Added AccountStatusChecker component to periodically verify account status and refresh UI if restrictions are lifted.
- Updated middleware to streamline account status checks and handle restricted user redirection more effectively.
- Enhanced layout to include AccountStatusChecker for improved user experience during authentication.

Implement account status management and checks across components

---

app/thread/[threadId]/hooks/comments/notifications.ts
app/thread/[threadId]/hooks/comments/useComments.ts
components/notifications/NotificationDropdown.tsx
components/notifications/useNotifications.ts

- Introduced validation for notification data to ensure required fields are present before creation.
- Improved error handling and logging for notification creation process.
- Updated `notifyAuthor` function to handle both new comments and replies, including better logging and error management.
- Enhanced real-time notification subscription with improved error handling and reconnection logic.
- Increased notification fetch limit for better user experience.
- Added retry mechanism for connection issues in the notification dropdown component.

Enhance notification handling and comment functionality

---

app/api/create-forum/route.ts
app/forums/components/ForumComponentWrapper.tsx
app/thread/[threadId]/hooks/comments/notifications.ts
app/thread/[threadId]/hooks/comments/useComments.ts
lib/auth-actions.ts
lib/message-actions.ts
lib/useUserRole.ts

- Commented out console log statements across various API and component files to reduce noise in the logs.
- Improved error handling by removing unnecessary logging while maintaining essential error messages.
- Enhanced code readability and maintainability by streamlining logging practices.

Refactor logging in API and component files

---

app/(auth)/callback/route.ts
app/landing-page/components/SubforumBlock.tsx
components/notifications/useNotifications.ts

- Commented out console log statements in the callback route and SubforumBlock component to reduce log noise.
- Enhanced code readability by streamlining logging practices across the application.
- Maintained essential error handling while removing unnecessary logging for improved performance.

Refactor logging in callback and SubforumBlock components
